//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnoses
    {
        public int DiagnosesId { get; set; }
        public int Diagnosis { get; set; }
        public int AmbulatoryCard { get; set; }
    
        public virtual AmbulatoryCard AmbulatoryCard1 { get; set; }
        public virtual Diagnosis Diagnosis1 { get; set; }
    }
}
