//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordId { get; set; }
        public System.TimeSpan TimeVisit { get; set; }
        public bool Available { get; set; }
        public int Doctor { get; set; }
        public Nullable<int> Service { get; set; }
        public Nullable<int> Visit { get; set; }
        public Nullable<int> Pet { get; set; }
        public int Day { get; set; }
    
        public virtual Pet Pet1 { get; set; }
        public virtual Visit Visit1 { get; set; }
        public virtual ScheduleDay ScheduleDay { get; set; }
        public virtual Service Service1 { get; set; }
        public virtual UserSys UserSys { get; set; }
    }
}
